import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import Navbar from '../components/Navbar';
import Cards from '../components/Cards';
import PhotoGalleryComponent from '../components/PhotoSection';
import About from '../components/About';
import Image from 'next/image';
import { bgWrap } from '../styles/Home.module.css';
import Footer from '../components/Footer';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Eco Getaway</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="dns-prefetch"
          async="true"
          deferRel="icon"
          href="%PUBLIC_URL%/favicon.ico"
        />
        <link
          rel="dns-prefetch"
          async="true"
          deferRel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="dns-prefetch"
          async="true"
          deferRel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="dns-prefetch"
          async="true"
          deferRel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link
          rel="dns-prefetch"
          async="true"
          deferRel="manifest"
          href="/site.webmanifest"
        />
      </Head>
      <Navbar />
      <HeroSection />
      <Cards />
      <PhotoGalleryComponent />
      <About />
      <Footer />
    </div>
  );
}
