import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import Navbar from '../components/Navbar';
import Cards from '../components/Cards';
import PhotoGalleryComponent from '../components/PhotoSection';
import About from '../components/About';
import Image from 'next/image';
import { bgWrap } from '../styles/Home.module.css';
import Background from '../components/background';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eco Getaway</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#00aba9" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <Background />
      <Navbar />
      <HeroSection />
      <PhotoGalleryComponent />
      <Cards />
      <About />
      <Footer />
    </div>
  );
}
